Add a smart contracts design document
hiero-ledger/hiero-mirror-node pull request #2638
Opened 2021-10-05 22:12 UTC by steven-sheehy

**Description**:
Add a smart contracts design document

**Related issue(s)**:

Fixes #2567 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2021-10-07 20:33 UTC, ijungmann commented on docs/design/smart-contracts.md
> +with smart contraction transactions in its database. With the
nit: assuming this is a typo
```suggestion
with smart contract transactions in its database. With the
```

2021-10-07 20:34 UTC, ijungmann commented on docs/design/smart-contracts.md
> +to bring high speed smart contract execution to the Hedera network, its become more important to ensure the mirror node
nit:
```suggestion
to bring high speed smart contract execution to the Hedera network, it's become more important to ensure the mirror node
```

2021-10-07 20:35 UTC, ijungmann commented on docs/design/smart-contracts.md
> +- Enhance the REST API to retrieve smart contracts and its execution results
```suggestion
- Enhance the REST API to retrieve smart contracts and their execution results
```

2021-10-07 23:02 UTC, ijungmann commented on docs/design/smart-contracts.md
> +      "auto_renew_period": 7776000,
Should we do something similar to `/tokens` vs `/tokens/{id}` and reduce the contracts list to just the identifier and critical data?

2021-10-07 23:06 UTC, ijungmann commented on docs/design/smart-contracts.md
> +      ],
Having a list within a list here concerns me a bit, I think I'm in favor of the `/contracts/{id}/results/{timestamp}` as mentioned in the questions.

2021-10-08 00:21 UTC, steven-sheehy commented on docs/design/smart-contracts.md
> +with smart contraction transactions in its database. With the
Yikes, fixed

2021-10-08 00:22 UTC, steven-sheehy commented on docs/design/smart-contracts.md
> +to bring high speed smart contract execution to the Hedera network, its become more important to ensure the mirror node
Fixed

2021-10-08 00:22 UTC, steven-sheehy commented on docs/design/smart-contracts.md
> +- Enhance the REST API to retrieve smart contracts and its execution results
Done

2021-10-08 00:22 UTC, steven-sheehy commented on docs/design/smart-contracts.md
> +);
Swapped to inherits

2021-10-08 00:23 UTC, steven-sheehy commented on docs/design/smart-contracts.md
> +```
I don't think we even use that one on entity table :|

2021-10-08 00:29 UTC, steven-sheehy commented on docs/design/smart-contracts.md
> +insert the old row to the history table after setting the old row's consensus period to end (exclusively) at the new
Sure, done

2021-10-08 00:30 UTC, steven-sheehy commented on docs/design/smart-contracts.md
> +create index if not exists contract_history__valid_range on contract_history using gist (valid_range);
This will be created by #2630

2021-10-08 14:05 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +2. Should there be a `/api/v1/contracts/{id}/results/{timestamp}`? Or should we limit results to a small amount?
DEX contracts will quickly blow up in results counts.
I'd suggest returning a configurable latest x call results for the given contract for `/api/v1/contracts/{id}/results`

The additional `/api/v1/contracts/{id}/results/{timestamp}` is valuable also.
Also under this endpoint showing all logs is acceptable

2021-10-08 14:14 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +3. What will externalization of the contract state in the transaction record look like?
This is also another place that will result in high data generation depending on the granularity we choose.
Are we interested in only the current state or would we also want to capture the change and the action that caused it?

2021-10-08 14:21 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +6. How should we allow searching by topics?
By exposing a logs endpoint with topic info there may be an explicit expectation given historical web3 usage.
In practice DApps heavily rely on the ability to filter on logs by topics in near real time.
If we go with the `json-rpc` addition then it's sufficient for devs to looks there and not have to add search capability immediately. 
If not we may want to add searching on the API side.
If we add searching it should rely on a timestamp range of consideration, for which we can add a limit of how wide that is.
We may also want to consider a rate limit on the search endpoint in that case.

2021-10-08 15:07 UTC, xin-hedera commented on docs/design/smart-contracts.md
> +  topics              bytea array default '{}' not null,
from the requirements doc, we need to support "query / filter based on 5 fields", is it out of scope?

2021-10-08 15:33 UTC, steven-sheehy commented on docs/design/smart-contracts.md
> +      "auto_renew_period": 7776000,
I was thinking that the rule should be that the list can contain any data from the table that you're already querying. We're already querying contracts so showing a few more fields from that shouldn't be too costly. But showing the bytecode that's in another table and can be quite large so only show for individual.

We might consider adding more fields to token list in the future if it meets the criteria.

2021-10-08 15:37 UTC, steven-sheehy commented on docs/design/smart-contracts.md
> +  file_id         bigint null,
They're already present in the `contract_result.gas_limit` and `contract_result.function_parameters`. These two can't change via an update transaction so it doesn't make sense to duplicate them over time. They are essentially a function call just like contract call so I put in results and normalized it with contract call transaction.

2021-10-08 15:38 UTC, steven-sheehy commented on docs/design/smart-contracts.md
> +  consensus_timestamp  nanos_timestamp primary key not null,
Adjusted

2021-10-08 15:38 UTC, steven-sheehy commented on docs/design/smart-contracts.md
> +  consensus_timestamp nanos_timestamp          not null,
Adjusted

2021-10-08 15:42 UTC, steven-sheehy commented on docs/design/smart-contracts.md
> +      "timestamp": {
I kind of liked `timestamp.from` and `timestamp.to`

2021-10-08 15:47 UTC, steven-sheehy commented on docs/design/smart-contracts.md
> +3. What will externalization of the contract state in the transaction record look like?
Still being designed. Will need to ask product about that. Not going to be implemented this sprint so doesn't block this design doc.

2021-10-08 15:50 UTC, ijungmann commented on docs/design/smart-contracts.md
> +```
Yeah, I didn't really see it being applied anywhere.  Cool, we'll skip it then.

2021-10-08 15:51 UTC, ijungmann commented on docs/design/smart-contracts.md
> +create table if not exists contract_result
Sure, makes sense.

2021-10-08 16:17 UTC, steven-sheehy commented on docs/design/smart-contracts.md
> +      "log_info": [
I dropped the log info and only show it in `api/v1/contracts/{id}/results/{timestamp}`. I don't think the counts are worth the extra join.

2021-10-08 16:48 UTC, xin-hedera requested changes

2021-10-08 16:48 UTC, xin-hedera commented on docs/design/smart-contracts.md
> +      "topic": [
```suggestion
      "topics": [
```

2021-10-08 16:48 UTC, xin-hedera commented on docs/design/smart-contracts.md
> +        "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
nit: some byte array have `0x` prefix some don't

2021-10-08 16:52 UTC, steven-sheehy commented on docs/design/smart-contracts.md
> +6. How should we allow searching by topics?
Bloom filters aren't currently populated.

2021-10-08 17:59 UTC, steven-sheehy commented on docs/design/smart-contracts.md
> +      "topic": [
Changed

2021-10-08 21:26 UTC, ijungmann commented on docs/design/smart-contracts.md
> +1. Is there a way to figure out which file belongs to which contract to back-fill data? No
nit: Should this be moved to `Non-Goals` or elsewhere since there's an answer to the question?

2021-10-08 22:44 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +6. How should we allow searching by topics?
JSON-RPC only would be best. Let's see

2021-10-08 22:46 UTC, Nana-EC approved these changes
LGTM

2021-10-11 14:06 UTC, xin-hedera approved these changes
LGTM

2021-10-11 14:33 UTC, merged