Add contract database schema
hiero-ledger/hiero-mirror-node pull request #2674
Opened 2021-10-12 23:14 UTC by steven-sheehy

**Description**:
- Add contract schema as per the [design document](https://github.com/hashgraph/hedera-mirror-node/blob/main/docs/design/smart-contracts.md)
- Fix some contract entities appearing as accounts
- Populate `contract.obtainer_id` from the non-fee paying entity associated with a contract delete
- Populate `contract_result.amount` from the aggregated non-fee crypto transfers associated with contract create and call transactions

**Related issue(s)**:

Fixes #2629 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2021-10-14 03:45 UTC, steven-sheehy commented on docs/design/smart-contracts.md
> -  "initial_balance": 100,
Dropped `contract.initial_balance` in favor of a normalized value in `contract_result.amount`. If I didn't, contract create results would either be null or duplicate the contract initial balance.

2021-10-14 03:48 UTC, steven-sheehy commented on docs/design/smart-contracts.md
> -) inherits (entity);
TimescaleDB and CitusDB do not support distributed inherited tables. So we have to use `like` and will add a test in the parser PR to verify "child" table stays in sync with "parent" table.

2021-10-14 17:06 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.46.3__smart_contracts.sql
> +update only entity e
nit:
```suggestion
update entity e
```

2021-10-14 17:14 UTC, xin-hedera commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__time_scale_init.sql
> +comment on table contract_log is 'Contract entity';
comment is not for `contract` table

2021-10-14 17:38 UTC, xin-hedera commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/domain/ContractResult.java
> +
are we going to keep the `call_result` column?

2021-10-14 19:31 UTC, ijungmann reviewed
One question, one nit, otherwise LGTM.

2021-10-14 19:31 UTC, ijungmann commented on docs/design/smart-contracts.md
> +  like entity,
If we're going to use `like` for this table, should we go ahead and remove `entity` fields after that do not apply to contracts, such as `max_automatic_token_associations`?

2021-10-14 19:31 UTC, ijungmann commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__time_scale_init.sql
> +);
Could add a comment for `contract_history` just to keep with all tables having a comment.

2021-10-14 20:44 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v2/V2.0.0__time_scale_init.sql
> +);
There was a comment, it just had the wrong table in the statement. Fixed

2021-10-14 21:58 UTC, Nana-EC requested changes
Looking good. 
Some potential query migration improvements for consideration

2021-10-14 21:58 UTC, Nana-EC commented on docs/design/smart-contracts.md
> +  like entity,
Similar thought, `submit_key` would also need to be dropped from `contract`. 
Either we drop those columns now or later all at once when each entity type has been moved out of entity

2021-10-14 21:58 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            ContractResult contractResult = new ContractResult();
nit: could use a shared method so Contract creation is in one location
```suggestion
            private void insertContract(long consensusTimestamp, ByteString parameters,
                                       ContractFunctionResult contractFunctionResult, long gasLimit) {
        ContractResult contractResult = new ContractResult();
        contractResult.setConsensusTimestamp(consensusTimestamp);
        contractResult.setFunctionParameters(Utility.toBytes(parameters));
        contractResult.setFunctionResult(contractFunctionResult.toByteArray());
        contractResult.setGasLimit(gasLimit);
        contractResult.setGasUsed(contractFunctionResult.getGasUsed());
        entityListener.onContractResult(contractResult);
    }
```

2021-10-14 21:58 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.46.3__smart_contracts.sql
> +with contract_transaction as (
why update contract entities only to then delete them.
Could we skip the entity update and do it in one go like below?

```suggestion
-- get contract entityIds from contract modifying transactions, then delete from entity table and insert deleted rows into contract
with contract_transactions as (
    select distinct entity_id
    from transaction
    where entity_id is not null
      and type in (7, 8, 9, 22)
),
contract_entities as (
    delete from only entity e where e.id = contract_transactions.entity_id returning *
)
insert
into contract
select auto_renew_account_id, auto_renew_period, created_timestamp, deleted, expiration_timestamp, id, key, memo, num, public_key, proxy_account_id, realm, shard, type, timestamp_range
from contract_entities;
```

2021-10-14 21:58 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.46.3__smart_contracts.sql
> +    from transaction t
Not sure how long this migration might take in mainnet but the `CONTRACTDELETEINSTANCE` transactions would be a subset of the `contract_transactions` query.
You could make `contract_transactions` a temp table and use it in both places instead of rescanning transactions.

Depending on the size it might be faster.

2021-10-14 21:58 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.46.3__smart_contracts.sql
> +    from transaction t
Could also be reused in the last query of file also as `CONTRACTCALL` and `CONTRACTCREATEINSTANCE` transactions are also subsets

2021-10-14 23:39 UTC, steven-sheehy commented on docs/design/smart-contracts.md
> +  topic3              text   null,
hibernate-types doesn't support `bytea[]`. Also, since there's only max 4 it makes sense to flatten them out and make them easier to index and search. We also want to use a postgresql bloom filter which doesn't support arrays or bytea, so we change to text.

2021-10-14 23:56 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.46.3__smart_contracts.sql
> +    from transaction t
They're not a subset. These are contract delete while the `contract_transactions` are just contract create and call transactions. Since there's an index on type it's pretty fast.

2021-10-15 01:51 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +            ContractResult contractResult = new ContractResult();
Okay

2021-10-15 01:52 UTC, Nana-EC commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.46.3__smart_contracts.sql
> +with contract_transaction as (
Agreed, better safe than sorry.
I'm okay with the separate steps

2021-10-15 03:05 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/resources/db/migration/v1/V1.46.3__smart_contracts.sql
> +    from transaction t
Changed to use a temp table

2021-10-15 15:34 UTC, Nana-EC approved these changes
LGTM

2021-10-15 15:48 UTC, merged