Combine realmNum and topicNum in TopicMessage ingestion and streaming
hiero-ledger/hiero-mirror-node pull request #2712
Opened 2021-10-18 16:26 UTC by Nana-EC

**Description**:
The `topic_message` table currently utilizes the split out entityId format.
This results in more columns being needed and therefore larger table sizes.

- Combine `realm_num` and `topic_num` into `topic_id` in TopicMessage domain
- Add a flyway migration to encode columns `realm_num` and `topic_num` and populate `topic_id` in `topic_messages` table
- Update importer ingestion flow to populate new field
- Update grpc streaming flow to subscribe and publish on topics using new id format

**Related issue(s)**:

Fixes #2456 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2021-10-18 21:09 UTC, steven-sheehy requested changes

2021-10-18 21:09 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/redis/RedisEntityListener.java
>      // For now, we assume realm is zero. Once we optimize TopicMessage to store encoded ID we can use that instead.
Drop comment

2021-10-18 21:09 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/entity/EntityRecordItemListener.java
> +        topicMessage.setTopicId(EntityId.of("0.0." + topicId.getTopicNum(), EntityTypeEnum.TOPIC));
```suggestion
        topicMessage.setTopicId(EntityId.of(topicId));
```

2021-10-18 21:09 UTC, steven-sheehy commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/converter/DigestAlgorithmSerializer.java
> +public class DigestAlgorithmSerializer extends JsonSerializer<DigestAlgorithm> {
This class seems to be unused

2021-10-18 21:09 UTC, steven-sheehy commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/util/EntityIdEndec.java
> +@Log4j2
Not used

2021-10-18 21:09 UTC, steven-sheehy commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/util/EntityIdEndec.java
> +public final class EntityIdEndec {
I've never liked this class. Would prefer it just be in `EntityId` even if it's just a util class for grpc since we're not modeling the domain with `EntityId` there.

2021-10-18 21:09 UTC, steven-sheehy commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/util/EntityIdEndec.java
> +    public static Long encode(long shardNum, long realmNum, long entityNum) {
This class needs a test and should use `@UtilityClass`

2021-10-18 21:09 UTC, steven-sheehy commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/controller/ConsensusController.java
> +            throw new IllegalArgumentException("Invalid entity ID");
Needs a test. Would prefer this logic be pushed into `EntityId.decode(TopicID)` and tested there.

2021-10-18 22:53 UTC, ijungmann reviewed
Looks good, nothing to comment on other than what has been noted by others.

2021-10-18 23:10 UTC, Nana-EC commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/repository/EntityRepository.java
> -    @Cacheable(cacheNames = "entity", cacheManager = CacheConfiguration.ENTITY_CACHE, unless = "#result == null")
Actually, without perf testing I'd prefer to not drop the cache. Don't wanna make too many changes at once.
Will move cache to findById

2021-10-19 00:01 UTC, Nana-EC commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/GrpcProperties.java
> -    private long shard = 0;
Updated

2021-10-19 00:02 UTC, Nana-EC commented on hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/converter/DigestAlgorithmSerializer.java
> +public class DigestAlgorithmSerializer extends JsonSerializer<DigestAlgorithm> {
Removed

2021-10-19 00:02 UTC, Nana-EC commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/util/EntityIdEndec.java
> +@Log4j2
Removed

2021-10-19 00:02 UTC, Nana-EC commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/util/EntityIdEndec.java
> +public final class EntityIdEndec {
Renamed

2021-10-19 00:03 UTC, Nana-EC commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/util/EntityIdEndec.java
> +    public static Long encode(long shardNum, long realmNum, long entityNum) {
Tests added

2021-10-19 00:03 UTC, Nana-EC commented on hedera-mirror-grpc/src/main/java/com/hedera/mirror/grpc/controller/ConsensusController.java
> +            throw new IllegalArgumentException("Invalid entity ID");
Updated

2021-10-19 03:15 UTC, steven-sheehy approved these changes
LGTM

2021-10-19 15:24 UTC, merged