Contract get and list REST apis
hiero-ledger/hiero-mirror-node pull request #2717
Opened 2021-10-19 13:52 UTC by xin-hedera

**Description**:

This PR adds the contract get and list REST apis.

- Add the contract list REST api
- Add the contract get REST api
- Add new index to `file_data` table for query by file id and consensus timestamp
- Update openapi spec for the new apis

**Related issue(s)**:

Fixes #2631 

**Notes for reviewer**:

Note that there was #294 tracks the `file_data` ingestion issue, and previously we decided "wontfix".

File* transactions proto ids
```
       (16, 'FILEAPPEND', 3),
       (17, 'FILECREATE', 3),
       (18, 'FILEDELETE', 3),
       (19, 'FILEUPDATE', 3),
```

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2021-10-19 20:35 UTC, ijungmann commented on hedera-mirror-rest/contracts.js
> +    const positions = _.range(start, params.length + 1) // end is exclusive
Is `params.length + 1` the correct value here?  I keep looking at it and getting lost, I feel like it's supposed to be `contractIdInValues.length + 1`, but it's entirely possible I'm misunderstanding this logic.

2021-10-19 20:44 UTC, xin-hedera commented on hedera-mirror-rest/contracts.js
> +    const positions = _.range(start, params.length + 1) // end is exclusive
lodash doc:

`_.range([start=0], end, [step=1])`

`end` is exclusive, i.e, with the default step=1, it generates the array [start, start + 1, ..., end -1]

we can't use `contractidInValues.length` directly since `params` array may already have some elements.

2021-10-19 20:59 UTC, steven-sheehy requested changes

2021-10-19 20:59 UTC, steven-sheehy commented on hedera-mirror-rest/entityId.js
> +    // shard, realm, and num take 4, 4, and 8 bytes respectively from the left. The last 4 bytes are used for
This isn't correct. It's 4 bytes for shard, 8 bytes for realm and 8 for num. No empty 4 bytes at the end. Here's the output of a ContractInfoQuery:
```
 ContractInfo{contractId=0.0.2860544, accountId=0.0.2860544, contractAccountId=00000000000000000000000000000000002ba600, ...)
```

Here's the services [implementation](https://github.com/hashgraph/hedera-services/blob/5a1c2e2475781eb277b6c149dd6c92c3e34accdf/hedera-node/src/main/java/com/hedera/services/utils/EntityIdUtils.java#L183)

2021-10-19 20:59 UTC, steven-sheehy commented on hedera-mirror-rest/contracts.js
> +    `f.consensus_timestamp <= ${Contract.getFullName(Contract.CREATED_TIMESTAMP)}`,
This needs to skip all but the last sequence of file data transactions. That is, if there's file create F1, file append F2, file update F3, file append F4, then it should only return F3 and F4. In general, it should return the last file create or last file update followed by its related file appends.

2021-10-19 20:59 UTC, steven-sheehy commented on hedera-mirror-rest/contracts.js
> +    `from contract ${Contract.tableAlias}, file_data f`,
I'm not seeing how this is concatenating many file data into a single byte array. If there's one file create and 3 file appends associated with that file ID, it should return the contents of all 4 file data concatenated as a single byte array.

2021-10-19 21:15 UTC, xin-hedera commented on hedera-mirror-rest/entityId.js
> +    // shard, realm, and num take 4, 4, and 8 bytes respectively from the left. The last 4 bytes are used for
this is the proposed new format. I should change it back to the current one and change it when services implement the new format.

2021-10-19 21:27 UTC, ijungmann commented on hedera-mirror-rest/contracts.js
> +  }
It's outside the scope of this PR, but this would be good logic to move to a util class someday and make work for different filters, I know we have something that sort of does that, a big refactoring of that would be nice.

2021-10-19 21:29 UTC, ijungmann commented on hedera-mirror-rest/contracts.js
> +        condition = `not ${timestampRangeColumn} @> ${position}`;
I think I'd like that (and the `&&`) as comments in the code.

2021-10-19 21:42 UTC, xin-hedera commented on hedera-mirror-rest/contracts.js
> +    `f.consensus_timestamp <= ${Contract.getFullName(Contract.CREATED_TIMESTAMP)}`,
will fix

2021-10-19 21:43 UTC, xin-hedera commented on hedera-mirror-rest/contracts.js
> +  }
was tempted to add this to utils but realized it'll touch many test cases for other endpoints, so it's better to leave it to a dedicated refactor ticket.

2021-10-19 22:04 UTC, ijungmann commented on hedera-mirror-rest/contracts.js
> +  }
I agree.  There's [a ticket to do](https://github.com/hashgraph/hedera-mirror-node/issues/1653) that we'll get to some day

2021-10-20 21:02 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/entityId.test.js
> +  test('0.0.7', () => {
nit: Add check for `EntityId.of(0n, 0n, 0n)`

2021-10-20 21:19 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-05-specific-id-not-contract-id.spec.json
> +  "description": "Contract api calls for a specific contract using contract id, not found",
nit: This is more of an entity type mismatch
```suggestion
  "description": "Contract api calls for a specific contract using contract id, matching type not found",
```
Also maybe rename file to `...-not-contract-entity-type.spec.json` so it's more clear

2021-10-20 21:22 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +          type: string
```suggestion
          $ref: '#/components/schemas/Timestamp'
```

2021-10-20 21:22 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +          type: string
```suggestion
          $ref: '#/components/schemas/Timestamp'
```

2021-10-20 21:23 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +        timestamp:
Move this to Schema as `timestamp_range` and reuse here as it will be reused for the other entity tables

2021-10-20 21:31 UTC, Nana-EC commented on hedera-mirror-rest/contracts.js
> +const fileDataQuery = `select string_agg(f.file_data, '' order by f.consensus_timestamp) bytecode
Replace column names, table name and alias with `Contract` and `FileData` model call
I'd like us to standardize on this.

2021-10-20 21:34 UTC, Nana-EC commented on hedera-mirror-rest/utils.js
> +  if (byteArray === null) {
nit: use `isnil` for coverage of undefined also
```suggestion
  if (_.isnil(byteArray)) {
```

2021-10-21 22:30 UTC, steven-sheehy requested changes

2021-10-21 22:30 UTC, steven-sheehy commented on hedera-mirror-rest/contracts.js
> +    `from contract ${Contract.tableAlias}, contract_file cf`,
Should we have some short circuit where clause for when contract.file_id is not null since that is the predominate value right now?

2021-10-21 22:30 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        type: string
We should define a regex. There should already be one. Can you have `contractIdPathParam` inherit from a generic entity id type?

2021-10-21 22:30 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +    contractIdQueryParam:
Needs to define allowable regex and hopefully inherit from a common entity id query param type

2021-10-21 22:30 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          type: string
timestamp range from and to should use timestamp type:
```suggestion
          $ref: '#/components/schemas/Timestamp'
```

2021-10-21 22:30 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        - admin_key
Do we normally mark response fields as required? And does required just mean the key must be present but not necessarily the value?

2021-10-21 22:30 UTC, steven-sheehy commented on hedera-mirror-rest/__tests__/specs/contracts-12-contract-id.spec.json
> +        "file_data": [12, 11, 10, 9, 8, 7, 255],
We can probably avoid populating file_data for contract list tests to reduce unnecessary code/config.

2021-10-25 21:32 UTC, merged