HIP-21 Address book REST API
hiero-ledger/hiero-mirror-node pull request #3442
Opened 2022-03-25 15:41 UTC by Nana-EC

**Description**:
[HIP-21](https://github.com/hashgraph/hedera-improvement-proposal/pull/223) describes the addition of an endpoint to help retrieve address book for state proof and awareness of consensus contributing nodes

- Add address book related models `AddressBook` , `AddressBookEntry` and `AddressBookServiceEndpoint`
- Add `NetworkNode` model to represent combined `address_book`, `address_book_entry` and `address_book_service_endpoint` table row combination
- Add `NetworkRoutes` 
- Add `networkNodeService` to manage DB call logic
- Add view model logic
  - `NetworkViewModel` to manage format logic of addressBooks
  - Add `AddressBookServiceEndpointViewModel` component
- Add `networkController` to handle http to service call logic for network related calls
- Add `NODE_ID` and `FILE_ID` filter constants to `constants` and `utils`
- Remove `network.js` file and move logic into `NetworkController`, NetworkService` and `NetworkSupplyViewModel`
- Add new endpoint to OpenApi
- Add spec tests and update `utilsFilters.test`

**Related issue(s)**:

Fixes #946 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-03-28 21:25 UTC, xin-hedera requested changes

2022-03-28 21:25 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +
use `Array.prototype.includes` if possible. And shouldn't we support '0.0.101', '0.0.102', and other formats?

2022-03-28 21:25 UTC, xin-hedera commented on hedera-mirror-rest/viewmodel/addressBookServiceEndpointViewModel.js
> +class AddressBookServiceEndpoint {
```suggestion
class AddressBookServiceEndpointViewModel {
```

2022-03-28 21:25 UTC, xin-hedera commented on hedera-mirror-rest/viewmodel/networkNodeViewModel.js
> +    this.public_key = utils.nsToSecNs(networkNode.addressBookEntry.publicKey);
perhaps just base64 encoding

```suggestion
    this.public_key = utils.nsToSecNs(networkNode.addressBookEntry.publicKey);
```

2022-03-28 21:25 UTC, xin-hedera commented on hedera-mirror-rest/viewmodel/networkSupplyViewModel.js
> +   * @param {Number} totalSupply
```suggestion
   * @param {BigInt} totalSupply
```

2022-03-28 21:25 UTC, xin-hedera commented on hedera-mirror-rest/controllers/networkController.js
> +        [constants.filterKeys.TIMESTAMP]: lastRow.timestamp.from,
why is it a multi-column pagination on node id then timestamp? Isn't that we should just retrieve info for network nodes that is valid at the specified timestamp?

2022-03-28 21:58 UTC, xin-hedera commented on hedera-mirror-rest/controllers/networkController.js
> +          );
we should limit the supported `timestamp` operators for the most common use cases that users normally want to get either the latest network address book info or the network address book info valid at a specific timestamp.

2022-03-28 22:08 UTC, xin-hedera requested changes

2022-03-28 22:08 UTC, xin-hedera commented on hedera-mirror-rest/service/networkNodeService.js
> +  static mirrorNodeAddressBookFileID = 102;
unused?

2022-03-28 22:08 UTC, xin-hedera commented on hedera-mirror-rest/service/networkNodeService.js
> +      order by ${AddressBookServiceEndpoint.PORT} desc
```suggestion
      order by ${AddressBookServiceEndpoint.IP_ADDRESS_V4} desc, ${AddressBookServiceEndpoint.PORT} desc
```
perhaps `asc` is better

2022-03-28 22:08 UTC, xin-hedera commented on hedera-mirror-rest/service/networkNodeService.js
> +   endpoints as (
why not fold this cte into the `entries` cte? what it does is retrieves the service endpoints for a node at the consensus timestamp. Folding into the `entries` cte can avoid the join here and the join in the main query, so it's easier to read.

2022-03-29 16:30 UTC, steven-sheehy requested changes

2022-03-29 16:30 UTC, steven-sheehy commented on hedera-mirror-rest/viewmodel/networkNodeViewModel.js
> +    this.node_cert_hash = utils.encodeBase64(networkNode.addressBookEntry.nodeCertHash);
Should be hex as in the HIP and since hashes are generally encoded in hex. Note that the underlying bytea is already hex encoded. Pseudo code:

```suggestion
    this.node_cert_hash = '0x' + decodeHex(networkNode.addressBookEntry.nodeCertHash).toString();
```

Please confirm the output matches the node cert hash in the [docs](https://docs.hedera.com/guides/mainnet/mainnet-nodes).

2022-03-29 16:30 UTC, steven-sheehy commented on hedera-mirror-rest/utils.js
> +const addressBookFileIdPattern = /101|102/;
This would match `0.0.100102`. This needs to be exact. Can we not parse it and check the num?

2022-03-29 16:30 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/networkController.js
> +        case constants.filterKeys.TIMESTAMP:
Please remove this parameter. It is not in the HIP or the ticket. We don't want to expose any non-latest address books.

2022-03-29 16:30 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/networkController.js
> +        [constants.filterKeys.TIMESTAMP]: lastRow.timestamp.from,
We should only use node_id to iterate over. Even if we were to later expose a timestamp param we would just have it return the list of nodes for the latest address book within the timestamp period.

2022-03-29 17:42 UTC, matheus-dallrosa commented on hedera-mirror-rest/api/v1/openapi.yml
> +        memo:
Memo does not have a schema? What is its max length?

2022-03-29 18:13 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +      ? Buffer.from(addressBookEntryInput.node_cert_hash, 'utf-8')
Fixed

2022-03-29 18:13 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +    memo: 1000,
Updated

2022-03-29 18:13 UTC, Nana-EC commented on hedera-mirror-rest/model/addressBook.js
> +const _ = require('lodash');
Removed

2022-03-29 18:18 UTC, Nana-EC commented on hedera-mirror-rest/server.js
> +// const network = require('./network');
Removed

2022-03-29 18:18 UTC, Nana-EC commented on hedera-mirror-rest/utils.js
> +
Updated

2022-03-29 18:18 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/addressBookServiceEndpointViewModel.js
> +class AddressBookServiceEndpoint {
Updated

2022-03-29 18:19 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/networkNodeViewModel.js
> +    this.public_key = utils.nsToSecNs(networkNode.addressBookEntry.publicKey);
Updated

2022-03-29 18:19 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/networkSupplyViewModel.js
> +   * @param {Number} totalSupply
Updated

2022-03-29 18:20 UTC, Nana-EC commented on hedera-mirror-rest/controllers/networkController.js
> +        [constants.filterKeys.TIMESTAMP]: lastRow.timestamp.from,
Will be discussing this with team.
We could take an `account_balance` approach

2022-03-29 18:20 UTC, Nana-EC commented on hedera-mirror-rest/controllers/networkController.js
> +          );
Open to reducing functionality until it's needed

2022-03-29 18:21 UTC, Nana-EC commented on hedera-mirror-rest/service/networkNodeService.js
> +  static mirrorNodeAddressBookFileID = 102;
Removed

2022-03-29 18:21 UTC, Nana-EC commented on hedera-mirror-rest/server.js
> +// const network = require('./network');
Removed

2022-03-29 18:39 UTC, Nana-EC commented on hedera-mirror-rest/controllers/networkController.js
> +  getSupply = async (req, res) => {
Meant to delete, will do

2022-03-29 20:53 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/networkNodeViewModel.js
> +    this.public_key = utils.nsToSecNs(networkNode.addressBookEntry.publicKey);
Had fixed the timestamp issue and will add the hex logic

2022-03-29 21:53 UTC, Nana-EC commented on hedera-mirror-rest/utils.js
> +const addressBookFileIdPattern = /101|102/;
Updated logic already with exact matches

2022-03-29 21:59 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +        memo:
This was actually deprecated so in current versions won't exist but we maintain for past versions.
In those cases I believe the max would be for a string value of `0.0.xx` i.e 6 chars and therefore 12 bytes I believe.

2022-03-30 00:47 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/networkNodeViewModel.js
> +    this.public_key = utils.nsToSecNs(networkNode.addressBookEntry.publicKey);
Actually it's a hex with the missing `0x` so i've added that

2022-03-30 17:14 UTC, Nana-EC commented on hedera-mirror-rest/controllers/networkController.js
> +        [constants.filterKeys.TIMESTAMP]: lastRow.timestamp.from,
Updated

2022-03-30 17:14 UTC, Nana-EC commented on hedera-mirror-rest/controllers/networkController.js
> +        case constants.filterKeys.TIMESTAMP:
Removed

2022-03-30 17:15 UTC, steven-sheehy commented on hedera-mirror-rest/viewmodel/networkNodeViewModel.js
> +    this.node_id = Number(networkNode.addressBookEntry.nodeId);
Nevermind, forgot about parsing limitation

2022-03-30 17:16 UTC, Nana-EC commented on hedera-mirror-rest/controllers/networkController.js
> +  getSupply = async (req, res) => {
Deleted

2022-03-30 17:16 UTC, Nana-EC commented on hedera-mirror-rest/constants.js
> +  ADDRESS_BOOK_FILE_ID: 'addressbook.file.id',
Updated

2022-03-30 17:17 UTC, Nana-EC commented on hedera-mirror-rest/service/networkNodeService.js
> +   endpoints as (
Folded in.

2022-03-30 17:17 UTC, Nana-EC commented on hedera-mirror-rest/service/networkNodeService.js
> +      order by ${AddressBookServiceEndpoint.PORT} desc
Updated

2022-03-30 17:17 UTC, Nana-EC commented on hedera-mirror-rest/controllers/networkController.js
> +          );
timestamp no longer applicable

2022-03-30 17:43 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/service/networkNodeService.test.js
> +     limit $2`;
this can be further simplified:

```sql
with adb as (
  select start_consensus_timestamp, end_consensus_timestamp, file_id
  from address_book 
  where file_id = $1
  order by start_consensus_timestamp desc limit 1
)
select
  abe.description,
  abe.memo,
  abe.node_id,
  abe.node_account_id,
  abe.node_cert_hash,
  abe.public_key,
  adb.file_id,
  adb.start_consensus_timestamp,
  adb.end_consensus_timestamp,
  coalesce((
    select json_agg(jsonb_build_object('ip_address_v4', ip_address_v4, 'port', port))
    from address_book_service_endpoint abse
    where abse.consensus_timestamp = abe.consensus_timestamp and abse.node_id = abe.node_id
  ), '[]') as service_endpoints
from address_book_entry abe
join adb
  on abe.consensus_timestamp = adb.start_consensus_timestamp
order by abe.node_id asc, abe.start_consensus_timestamp asc
limit $2
```

2022-03-30 18:14 UTC, xin-hedera commented on hedera-mirror-rest/controllers/networkController.js
> +      response.links.next = utils.getPaginationLink(req, false, last, order, {[constants.filterKeys.NODE_ID]: true});
`NODE_ID` shouldn't be an `inclusive` key since there should be only one row for each `NODE_ID`

2022-03-30 19:37 UTC, Nana-EC commented on hedera-mirror-rest/controllers/networkController.js
> +      response.links.next = utils.getPaginationLink(req, false, last, order, {[constants.filterKeys.NODE_ID]: true});
Fixed

2022-03-30 19:37 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/service/networkNodeService.test.js
> +     limit $2`;
Adopted

2022-03-30 23:43 UTC, xin-hedera requested changes

2022-03-30 23:43 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/network-nodes-04-all-params.spec.json
> +      "next": "/api/v1/network/nodes?file.id=102&node.id=0&limit=1&order=asc"
`next` should be null
and we need another spec with non-null `next` link

2022-03-30 23:43 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +          $ref: '#/components/responses/NotFoundError'
will there be a 404 response?

2022-03-30 23:43 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +          example: "AAEBAwuqAwzB"
example redundant and it's a base64 string?

2022-03-30 23:43 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +        balance: 50211
wrong example

2022-03-31 00:27 UTC, steven-sheehy requested changes

2022-03-31 00:27 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          description: base64 encoded binary data
Hex encoded

2022-03-31 00:27 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          type: string
Description should denote hex encoded

2022-03-31 00:27 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        file_id:
We should probably add a description for each of these fields. Can do a partial copy from the `NodeAddress.proto`.

2022-03-31 00:27 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        type: integer
Isn't it technically a string since we support various operators? This should be expanded to show those operators.

2022-03-31 14:52 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +          $ref: '#/components/responses/NotFoundError'
Hmm, there's a case to be considered for if you filter on a single node, with no limit query.
However, that seem to fine grained, plus the main entity here is the addressBook which is sure to exist.
So, I think  can drop the 404 as N/A for now

2022-03-31 14:53 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +          example: "AAEBAwuqAwzB"
WiIl remove and make actual example below a string

2022-03-31 14:54 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/networkNodeViewModel.js
> +      : utils.addHexPrefix(networkNode.addressBookEntry.publicKey);
Agreed

2022-03-31 15:34 UTC, xin-hedera requested changes

2022-03-31 16:03 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/network-nodes-04-all-params.spec.json
> +      "next": "/api/v1/network/nodes?file.id=102&node.id=0&limit=1&order=asc"
Why would it be null? The response count equals the limit. So we provide a valid `next` even if it's possible to return an empty set based off of the db query.
Adding a next to the range spec

2022-03-31 16:18 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/network-nodes-04-all-params.spec.json
> +      "next": "/api/v1/network/nodes?file.id=102&node.id=0&limit=1&order=asc"
never mind, my misunderstanding :)

2022-03-31 17:06 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/network-nodes-04-all-params.spec.json
> +      "next": "/api/v1/network/nodes?file.id=102&node.id=0&limit=1&order=asc"
Added `next` to range spec

2022-03-31 17:06 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +          $ref: '#/components/responses/NotFoundError'
Removed 404

2022-03-31 17:06 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +          example: "AAEBAwuqAwzB"
Removed and updated

2022-03-31 17:06 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +        balance: 50211
Updated keys

2022-03-31 17:06 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/networkNodeViewModel.js
> +      : utils.addHexPrefix(networkNode.addressBookEntry.publicKey);
Updated

2022-03-31 17:06 UTC, Nana-EC commented on hedera-mirror-rest/service/networkNodeService.js
> +      )}, ${AddressBookEntry.getFullName(AddressBookEntry.CONSENSUS_TIMESTAMP)} ${nodeOrder}`,
Removed

2022-03-31 17:07 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +          description: base64 encoded binary data
Updated

2022-03-31 17:54 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +};
Updated

2022-03-31 17:54 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +          type: string
Updated

2022-04-01 03:06 UTC, steven-sheehy commented
Please add entry to new database section in rest api docs

2022-04-01 03:32 UTC, steven-sheehy requested changes

2022-04-01 03:32 UTC, steven-sheehy commented on hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js
> +      block_hash: utils.addHexPrefix(recordFile.hash, false),
Why would we ever want to return just `0x`?

2022-04-01 03:32 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        pattern: ^((eq|gt|gte|lt|lte):)?\d{1,19}?$
```suggestion
        pattern: ^((eq|gt|gte|lt|lte):)?\d{1,19}$
```

2022-04-01 03:32 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +          description: A non-sequential identifier for the node
It is sequential, though. You can probably just omit any reference to sequential/non-sequential

2022-04-01 03:32 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +        - $ref: '#/components/parameters/orderQueryParamDesc'
You changed it to ascending

2022-04-01 03:32 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/networkController.js
> +          limit = filter.value;
Each entry is quite large, perhaps about 1600 bytes. At 100 limit, returning 156K might be too much. We should enforce a higher max limit for this API. Perhaps default/max both 25? Or lower default as well 10/25?

2022-04-01 17:30 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js
> +      block_hash: utils.addHexPrefix(recordFile.hash, false),
We currently have `0x` as a response for a failed contract call result and possibly other contractResult cases. 
My original thought was the same as yours but I didn't want to create additional code churn.
I can update it to nullable if we're sure this is a bug

2022-04-01 17:42 UTC, Nana-EC commented on hedera-mirror-rest/controllers/networkController.js
> +          limit = filter.value;
I like 10/25. We can always bump it up later

2022-04-01 17:45 UTC, steven-sheehy commented on hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js
> +      block_hash: utils.addHexPrefix(recordFile.hash, false),
I think that's a bug. `0x` shouldn't be valid hex. But also we should always have a record file for a particular transaction and its hash should never be null. So it's probably a moot point in practice. So think we should return null for this case and keep the code cleaner.

2022-04-01 17:52 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +          description: A non-sequential identifier for the node
Updated

2022-04-01 17:52 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +        - $ref: '#/components/parameters/orderQueryParamDesc'
Updated

2022-04-01 17:52 UTC, Nana-EC commented on hedera-mirror-rest/controllers/networkController.js
> +          limit = filter.value;
Updated

2022-04-01 17:52 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +        pattern: ^((eq|gt|gte|lt|lte):)?\d{1,19}?$
Updated

2022-04-01 18:17 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js
> +      block_hash: utils.addHexPrefix(recordFile.hash, false),
Updated

2022-04-01 20:08 UTC, steven-sheehy requested changes

2022-04-01 20:08 UTC, steven-sheehy commented on docs/rest/README.md
> +| `/api/v1/network/nodes`                         | `address_book`, `address_book_entry`, `address_book_service_endpoints`                                       |
nit:
```suggestion
| `/api/v1/network/nodes`                         | `address_book`, `address_book_entry`, `address_book_service_endpoint`                                       |                                                              |
```

2022-04-01 20:08 UTC, steven-sheehy commented on hedera-mirror-rest/api/v1/openapi.yml
> +      description: The ID of the node id
nit:
```suggestion
      description: The ID of the node
```

2022-04-01 20:08 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/networkController.js
> +  },
```suggestion
```

2022-04-01 21:57 UTC, Nana-EC commented on hedera-mirror-rest/controllers/networkController.js
> +  },
Had this staged, just pushed.

2022-04-01 21:57 UTC, Nana-EC commented on hedera-mirror-rest/api/v1/openapi.yml
> +      description: The ID of the node id
Updated

2022-04-01 21:57 UTC, Nana-EC commented on docs/rest/README.md
> +| `/api/v1/network/nodes`                         | `address_book`, `address_book_entry`, `address_book_service_endpoints`                                       |
Fixed

2022-04-01 22:04 UTC, steven-sheehy approved these changes
LGTM

2022-04-04 14:41 UTC, xin-hedera approved these changes
LGTM

2022-04-04 16:05 UTC, merged