Token allowances REST api
hiero-ledger/hiero-mirror-node pull request #3464
Opened 2022-03-28 15:11 UTC by xin-hedera

**Description**:

This PR implements the token allowances REST api.

- Add token allowances REST api with multi-column pagination
- Fix crypto allowances REST api not accepting gt/gte/lt/lte query operators
- Remove `payer_account_id` from allowances response
- Remove `payerAccountId` from crypto allowances acceptance test
- Rename `amount` in crypto and token allowance view model to `amount_granted`

**Related issue(s)**:

Fixes #3247

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-03-28 16:19 UTC, xin-hedera commented on hedera-mirror-rest/utils.js
> +const gtLtPattern = /[gl]t[e]?:/;
we should switch to use `Array.prototype.includes`, did a benchmark, it's ~40 times faster than regex match.

2022-03-28 16:44 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/integration.test.js
> +      }
support a new `tests` section in the json integration test spec. The section is an array of `{"url": ..., "responseStatus": ..., "responseJson": ...}` so with a single set of data, we can support different urls with different expected response status and response.

2022-03-28 16:57 UTC, xin-hedera commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/AccountFeature.java
> -
sth wrong with my IDE config after I upgraded to intellij IDEA ultimate 2021.3.3

2022-03-28 17:18 UTC, xin-hedera commented on docs/design/allowances.md
> -      "payer_account_id": "0.0.1000",
should not expose `payer_account_id` since it doesn't provide allowance relevant info. Suppose the payer account id of approval/allowance transactions is the same as other transactions, it should be the `owner` in most cases but it can also be a different account.

2022-03-29 11:29 UTC, matheus-dallrosa commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +  const table = tokenAllowance.timestamp_range.endsWith(',)') ? 'token_allowance' : 'token_allowance_history';
I know this is only a setup code for tests, but could you put a comment on why you use one table instead of the other when the range finishes with `,)`.

2022-03-29 13:52 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/integrationDomainOps.js
> +  const table = tokenAllowance.timestamp_range.endsWith(',)') ? 'token_allowance' : 'token_allowance_history';
moved the logic to a function and added comment there

2022-03-29 14:18 UTC, Nana-EC requested changes

2022-03-29 14:52 UTC, xin-hedera commented on hedera-mirror-rest/controllers/tokenAllowanceController.js
> +module.exports = {
need to export the `Bound` class for testing purpose so can't set the exports to the `TokenAllowanceController` object.

2022-03-29 16:38 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +    TokenAllowance:
updated

2022-03-29 16:38 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +        $ref: '#/components/schemas/CryptoAllowance'
fixed

2022-03-29 16:39 UTC, xin-hedera commented on hedera-mirror-rest/controllers/tokenAllowanceController.js
> +class Bound {
seems possible, prefer to leave it to a separate ticket

2022-03-29 16:39 UTC, xin-hedera commented on hedera-mirror-rest/service/baseService.js
> +   * @param {{column: string, order: 'asc'|'desc'}} orderSpecs
added a `OrderSpec` class

2022-03-29 17:35 UTC, matheus-dallrosa commented on hedera-mirror-rest/service/entityService.js
> +        return await this.getAccountIdFromAlias(AccountAlias.fromString(accountIdString));
Nit: You can remove the `await` here.

2022-03-29 18:05 UTC, xin-hedera commented on hedera-mirror-rest/service/tokenAllowanceService.js
> +   * @return {string|null}
the return type is correct, it's either a string or value null. not sure what's the requested change

2022-03-29 18:07 UTC, xin-hedera commented on hedera-mirror-rest/service/entityService.js
> +        return await this.getAccountIdFromAlias(AccountAlias.fromString(accountIdString));
`getAccountIdFromAlias` is async

2022-03-29 18:10 UTC, xin-hedera commented on hedera-mirror-rest/service/tokenAllowanceService.js
> +    const {lower, inner, upper, order, ownerAccountId, limit} = query;
this ties to how we started to support 2-column pagination which translates to a 3-prong multi-union sql query. Since it's 3-prong, we call the 3 subqueries of the multi-union query `lower`, `inner`, and `upper`. Here, 

- `lower` is the filters used to generate the `lower` subquery
- `inner` is the filters used to generate the `inner` subquery
- `upper` is the filters used to generate the `upper` subquery

2022-03-30 20:15 UTC, Nana-EC commented on hedera-mirror-rest/controllers/tokenAllowanceController.js
> +class Bound {
that's fine

2022-03-30 20:16 UTC, Nana-EC commented on hedera-mirror-rest/service/baseService.js
> +   * @param {{column: string, order: 'asc'|'desc'}} orderSpecs
Okay, yeah preferred a class but didn't want to request too much code churn

2022-03-30 20:55 UTC, Nana-EC commented on hedera-mirror-rest/controllers/tokenAllowanceController.js
> +module.exports = {
Why not pull `Bound` class out.
It seems reusable and could be used in non multi-union query slows

2022-03-30 23:10 UTC, Nana-EC submitted a review, later dismissed
LG, I think a bit more documentation around the Bound and filter handling logic in the Service might be useful for maintainability

2022-03-30 23:10 UTC, Nana-EC commented on hedera-mirror-rest/controllers/tokenAllowanceController.js
> +class TokenAllowanceController extends BaseController {
For the `getXFilters` function of this class it might be useful to expand on the comments to give better comprehension when

2022-03-31 01:10 UTC, xin-hedera commented on hedera-mirror-rest/controllers/tokenAllowanceController.js
> +class TokenAllowanceController extends BaseController {
will give it a try

2022-03-31 19:20 UTC, xin-hedera commented on hedera-mirror-rest/service/tokenAllowanceService.js
> +   * @return {string|null}
fixed

2022-03-31 19:20 UTC, xin-hedera commented on hedera-mirror-rest/service/orderSpec.js
> +class OrderSpec {
moved to the new `sql` module

2022-03-31 19:28 UTC, xin-hedera commented on hedera-mirror-rest/controllers/tokenAllowanceController.js
> +module.exports = {
pulled it out to its own js file

2022-03-31 22:59 UTC, Nana-EC approved these changes

2022-04-01 00:14 UTC, steven-sheehy requested changes

2022-04-01 00:14 UTC, steven-sheehy commented on hedera-mirror-rest/viewmodel/cryptoAllowanceViewModel.js
> +    this.amount_granted = Number(cryptoAllowance.amount);
Why can't we have it in the base? In preparation for nft allowance?

2022-04-01 03:05 UTC, steven-sheehy commented
Please add entry to new database section in rest api docs

2022-04-01 20:52 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +        - $ref: '#/components/parameters/orderQueryParamDesc'
will fix the $ref, it should be `orderQueryParamDesc`

2022-04-01 20:53 UTC, xin-hedera commented on hedera-mirror-rest/viewmodel/cryptoAllowanceViewModel.js
> +    this.amount_granted = Number(cryptoAllowance.amount);
yes `NftAllowanceViewModel` most likely will extend from it

2022-04-01 21:21 UTC, xin-hedera commented on hedera-mirror-rest/api/v1/openapi.yml
> +        - $ref: '#/components/parameters/orderQueryParamDesc'
also created a bug ticket https://github.com/hashgraph/hedera-mirror-node/issues/3491
for the inconsistent default order of crypto allowances REST api, `desc` in code v.s. `asc` in design doc

2022-04-01 22:05 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2022-04-04 14:45 UTC, Nana-EC submitted a review, later dismissed
LGTM

2022-04-04 21:29 UTC, xin-hedera commented
The rosetta-api workflow failure is tracked here: #3510

2022-04-04 21:30 UTC, steven-sheehy approved these changes

2022-04-05 14:42 UTC, merged