Add network fee schedule REST API
hiero-ledger/hiero-mirror-node pull request #3881
Opened 2022-05-31 15:07 UTC by ar-conmit

Signed-off-by: Anton Rusev <anton.rusev.code@gmail.com>

**Description**:
Add new endpoint to retrieve network fees
- add endpoint `/network/fees`
- add model `FeeSchedule`
- add view model `FeeScheduleViewModel`
- add function `convertGasPriceToTinyBars`

**Related issue(s)**:

Fixes #3578 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-05-31 18:41 UTC, Nana-EC requested changes
Looking good.
Open API, test suggestions and controller improvement

2022-05-31 18:41 UTC, Nana-EC commented on hedera-mirror-rest/utils.js
> +const convertGasPriceToTinyBars = (gasPrice, hbarsPerTinyCent, centsPerHbar) => {
Add test cases for this.
Cover extremes and valid cases.
Verify proto and json example, if it's possible for a null.

May also want to guard against null/undefined params

2022-05-31 18:41 UTC, Nana-EC commented on hedera-mirror-rest/controllers/networkController.js
> +    const exchangeRate = await FileDataService.getExchangeRate(filterQuery);
Combine to make this call in parallel
```suggestion
    const [exchangeRate, feeSchedule] = await Promise.all([
      FileDataService.getExchangeRate(filterQuery),
      FileDataService.getExchangeRate(filterQuery)
    ]);
```

2022-05-31 18:41 UTC, Nana-EC commented on hedera-mirror-rest/controllers/networkController.js
> +   * Handler function for /network/fees API.
Add to OpenAPI spec.

2022-06-01 04:06 UTC, steven-sheehy requested changes

2022-06-01 04:06 UTC, steven-sheehy commented on hedera-mirror-rest/model/feeSchedule.js
> +    this.next_feeSchedule = this._normalize(currentAndNextFeeSchedule.nextFeeSchedule);
Even though the proto is a bit awkward, for future use it might be better to keep it in its default form instead of normalizing it and doing all mapping in the viewmodel. So this might become `this.feeSchedule = proto.CurrentAndNextFeeSchedule.decode(Buffer.from(feeSchedule.file_data, 'hex'));`.

2022-06-01 04:07 UTC, steven-sheehy commented
Need to set cache header in application.yml

2022-06-01 14:20 UTC, Nana-EC reviewed
Looks good.
Just a few nits that can be quickly resolved and i'm good to sign off

2022-06-01 14:20 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/network-fees-06-timestamp-ne.spec.json
> +  "description": "Network fees with no unsupported ne timestamp arg",
```suggestion
  "description": "Network fees with unsupported ne timestamp arg",
```

2022-06-01 14:20 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/network-fees-03-timestamp-upper-bound.spec.json
> +  "description": "Network fees with upper bound timestamp",
nit: urls also include eq case. So you can update the description or split the files. I say update the description since the response is the same as written
```suggestion
  "description": "Network fees with inner and upper bound timestamp",
```

2022-06-01 14:20 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/network-fees-02-order.spec.json
> +      "urls": ["/api/v1/network/fees", "/api/v1/network/fees?order=asc"],
```suggestion
      "url": "/api/v1/network/fees?order=asc",
```
or
```suggestion
      "urls": ["/api/v1/network/fees?order=ASC", "/api/v1/network/fees?order=asc"],
```

2022-06-01 14:21 UTC, Nana-EC requested changes
Unblocking. Since it's functional and deadline

2022-06-01 14:22 UTC, Nana-EC submitted a review, later dismissed

2022-06-01 15:27 UTC, steven-sheehy approved these changes

2022-06-01 15:27 UTC, steven-sheehy commented on hedera-mirror-rest/viewmodel/feeScheduleViewModel.js
> +        // make sure the gas price is converted successfully, otherwise something is wrong with gasPrive or exchange rate, so skip the current fee
```suggestion
        // make sure the gas price is converted successfully, otherwise something is wrong with gasPrice or exchange rate, so skip the current fee
```

2022-06-01 18:38 UTC, merged