Fix unsuccessful Ethereum transactions not found on contract results API
hiero-ledger/hiero-mirror-node pull request #3984
Opened 2022-06-24 13:10 UTC by ar-conmit

Signed-off-by: Anton Rusev <anton.rusev.code@gmail.com>

**Description**:

**Related issue(s)**:

Fixes #3954 

**Notes for reviewer**:
Example response:
```
{
  "amount": 0,
  "bloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "call_result": "0x",
  "contract_id": "0.0.1006",
  "created_contract_ids": [],
  "error_message": "INVALID_CONTRACT_ID",
  "from": "0x0000000000000000000000000000000000000002",
  "function_parameters": "0x",
  "gas_limit": 0,
  "gas_used": 0,
  "timestamp": "1655985454.224602715",
  "to": "0x00000000000000000000000000000000000003ee",
  "hash": "0x8fd6307a325ae86ae726bb4167319903662f4b933cf1875ad23a689739f5fb52",
  "block_hash": "0xe260af3a31c19ee7d5f728e45201696f3e5cf9daf036e5d37869665acbc8fbbc1e611e3a7d49df74e6816129f8e8705b",
  "block_number": 793,
  "logs": [],
  "result": 16,
  "transaction_index": 1,
  "state_changes": [],
  "status": "0x0",
  "access_list": "0x",
  "block_gas_used": 320000,
  "chain_id": "0x12a",
  "gas_price": "0x",
  "max_fee_per_gas": "0xdb",
  "max_priority_fee_per_gas": "0xdb",
  "r": "0x2661712d86a4f8217dd1ccc6eac333f6ebf817b9c89964ee16af76b79071082e",
  "s": "0x5f5b573d569a9556dfaf8bda7c325fabeaf1c0174277514e650661a73d097c45",
  "type": 2,
  "v": 1,
  "nonce": 1
}
```
**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2022-06-27 17:46 UTC, Nana-EC reviewed
Looks good.
Though I think we could better describe the scenario. It's less a mock and more of a default failure result we're falling back on

2022-06-27 17:46 UTC, Nana-EC commented on hedera-mirror-rest/controllers/contractController.js
> +        transaction.toAddress && transaction.toAddress.toString('hex') ? transaction.toAddress.toString('hex') : null,
nit: pull out toAddress conversion
```
const toAddress = transaction.toAddress ? transaction.toAddress.toString('hex') : null;
```
```suggestion
        toAddress ? toAddress : null,
```

2022-06-27 17:46 UTC, Nana-EC commented on hedera-mirror-rest/controllers/contractController.js
> +  getMockedContractResultByTransaction = (transaction) => {
nit: mocked doesn't really inform the scenario
```suggestion
  getDefaultFailureContractResultByTransaction = (transaction) => {
```

2022-06-27 17:46 UTC, Nana-EC commented on hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js
> +    isContractResultMocked
nit:
```suggestion
    isFailedContractResult
```

2022-06-27 20:49 UTC, xin-hedera requested changes

2022-06-27 20:49 UTC, xin-hedera commented on hedera-mirror-rest/controllers/contractController.js
> +      bloom: Buffer.alloc(256),
can make `Buffer.alloc(256)` to a constant. frequently alloc then garbage collect it may create performance issue

2022-06-27 20:49 UTC, xin-hedera commented on hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js
> +    }
not needed. once the block is removed, the new function parameter `isContractResultMocked` is not needed either.

2022-06-27 20:49 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/contracts-result-details-22-transactionid-or-hash-eth-tx-result-mocked.spec.json
> +    "result": 16,
the result should be a string. reverting the changes in `contractResultDetailsViewModel.js` should fix it

2022-06-27 20:49 UTC, xin-hedera commented on hedera-mirror-rest/__tests__/specs/contracts-result-details-22-transactionid-or-hash-eth-tx-result-mocked.spec.json
> +  "responseStatus": 206,
I believe this should be `200` instead of `206`. @Nana-EC can you look into it since I'm not sure the 206 missing contract call result should apply to this scenario or not?

2022-06-28 01:12 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/contractController.js
> +        transaction.toAddress && transaction.toAddress.toString('hex') ? transaction.toAddress.toString('hex') : null,
This is incorrect. The `contract_id` should always be the `shard.realm.num` format and not a hex number.

2022-06-28 06:19 UTC, ar-conmit commented on hedera-mirror-rest/__tests__/specs/contracts-result-details-22-transactionid-or-hash-eth-tx-result-mocked.spec.json
> +    "result": 16,
In the issue is pointed out that `result` should be the response code and the `error_message` should be the text of the response code

2022-06-28 07:00 UTC, ar-conmit commented on hedera-mirror-rest/controllers/contractController.js
> +        transaction.toAddress && transaction.toAddress.toString('hex') ? transaction.toAddress.toString('hex') : null,
`toAddress` is now replaced with `entityId` which is always a number or null

2022-06-28 07:00 UTC, ar-conmit commented on hedera-mirror-rest/controllers/contractController.js
> +        transaction.toAddress && transaction.toAddress.toString('hex') ? transaction.toAddress.toString('hex') : null,
`toAddress` is now replaced with `entityId`

2022-06-28 15:08 UTC, xin-hedera submitted a review, later dismissed
LGTM

2022-06-28 23:11 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/contractController.js
> +      contractId: transaction.entityId,
Technically if there's no contract result there's no `transaction.entityId` since it's populated from the `record.contractFunctionResult.contractID` in the importer for EthereumTransaction. So it's a bit useless to return this in this scenario. You can see this reflected in the original ticket's JSON response:

https://testnet.mirrornode.hedera.com/api/v1/transactions/0.0.2859100-1655309548-529823609?nonce=0

Recommend you revert query returning entityId and set null here.

```suggestion
      contractId: null,
```

2022-06-28 23:12 UTC, steven-sheehy commented on hedera-mirror-rest/controllers/contractController.js
> +      functionParameters: [],
nit: sort these fields

2022-06-28 23:54 UTC, Nana-EC commented on hedera-mirror-rest/__tests__/specs/contracts-result-details-22-transactionid-or-hash-eth-tx-result-mocked.spec.json
> +  "responseStatus": 206,
The 206 case was used when the ContractFunctionResult returned from the network was partial. In this case since there's none it can be 200

2022-06-29 00:01 UTC, Nana-EC submitted a review, later dismissed
LG

2022-06-29 06:13 UTC, ar-conmit commented on hedera-mirror-rest/controllers/contractController.js
> +      contractId: transaction.entityId,
Done

2022-06-29 06:14 UTC, ar-conmit commented on hedera-mirror-rest/__tests__/specs/contracts-result-details-22-transactionid-or-hash-eth-tx-result-mocked.spec.json
> +  "responseStatus": 206,
Done

2022-06-29 13:20 UTC, steven-sheehy approved these changes
LGTM

2022-06-29 13:27 UTC, merged