Add cache for web3 precompiles
hiero-ledger/hiero-mirror-node pull request #5721
Opened 2023-03-29 06:41 UTC by mustafauzunn

**Description**:

To significantly decrease the load on the DB, we add a cache mechanism for repositories in the web3 module.

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-03-29 17:40 UTC, steven-sheehy requested changes

2023-03-29 17:40 UTC, steven-sheehy commented on hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/repository/NftRepository.java
>  public interface NftRepository extends CrudRepository<Nft, NftId> {}
For all these repositories, we should override `findById` and any other method that we use in main code and only add cacheable to that. Otherwise we cache calls to save, delete, etc. that could break tests.

2023-03-30 21:36 UTC, steven-sheehy approved these changes

2023-03-30 22:39 UTC, steven-sheehy commented
There's failing web3 tests that need to be fixed.

2023-03-31 05:10 UTC, Nana-EC submitted a review, later dismissed

2023-03-31 07:10 UTC, IvanKavaldzhiev approved these changes
LGTM

2023-03-31 14:32 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +        cacheManager.getCache("custom_fee").clear();
Would prefer a generic cleanup of all cache managers in `Web3IntegrationTest` similar to the importer's [IntegrationTest](https://github.com/hashgraph/hedera-mirror-node/blob/9381ef88af3135918df3702111f213bea21a5019/hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/IntegrationTest.java#L116). This will fix this problem and ensure no future problems.

2023-03-31 15:45 UTC, xin-hedera approved these changes
LGTM

2023-03-31 16:51 UTC, steven-sheehy approved these changes

2023-03-31 16:51 UTC, merged