HIP-584: Transfer on estimate gas results in error 400
hiero-ledger/hiero-mirror-node pull request #6778
Opened 2023-08-29 13:01 UTC by natanasow

### Description

As a user, I would like to use HTS tokens via ERC20 interface. Gas estimation on the erc20 transfer is not working properly.

Prerequisites:
- token address - `0x0000000000000000000000000000000000000573`
- receiver (account created via hbar transfer) - id `1394` and evm address `0xa0e1d164c8027f8468d2643b714e0637ec2b283b`

PS: Base account creation had to be refactored because there is no test account with a valid evm address. All of the accounts are created with `AccountCreateTransaction` which results in an account with evm address that is just a long zero address of the account id. Creating an account with a valid evm address (not long zero) can be done via `TransferTransaction`.

### Solution

Return empty precompile result if the sender is missing && isEstimate = true && we have top level token call for transfer, approve, associate and dissociate. These contracts depend on the sender and will revert if this value is missing

**Related issue(s)**:

Fixes #6777 
Fixes #6824

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2023-09-14 03:01 UTC, Nana-EC commented
@0xivanov is this ready for review or are there a few items still keeping it in draft?

2023-09-14 04:55 UTC, 0xivanov commented
> @0xivanov is this ready for review or are there a few items still keeping it in draft?

There are more tests that need to be written.

2023-09-15 20:05 UTC, steven-sheehy requested changes

2023-09-15 20:05 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +    private final MirrorNodeClient mirrorClient;
Already in parent

2023-09-15 20:05 UTC, steven-sheehy commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +            newAccountId = new AccountId(accountInfo.accountId.num);
Why can't we just set `cryptocreatetransaction.alias = evmAddress` or proto ECDSA key if we want a non-long zero address? This would be more explicit and appropriate for a `createCryptoAccount` method.

2023-09-18 09:36 UTC, 0xivanov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimateFeature.java
> +    private final MirrorNodeClient mirrorClient;
removed

2023-09-18 09:38 UTC, 0xivanov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/client/AccountClient.java
> +            newAccountId = new AccountId(accountInfo.accountId.num);
Implemented the suggestion, that opened up more work because receiverSig is required when i set alias for some reason.
Besides that, i had to use the alias instead of the long zero in the other tests, because the mirror node requires the usage of alias if there is one.

2023-09-18 09:44 UTC, 0xivanov commented on hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/EstimatePrecompileFeature.java
> +                        asAddress(nonFungibleKycUnfrozenTokenId.toSolidityAddress()), asAddress(receiverAccountAlias));
I think spotlessApply is causing these changes

2023-09-18 18:42 UTC, steven-sheehy approved these changes
LGTM

2023-09-18 19:16 UTC, steven-sheehy requested changes
Getting 3 failures with this branch against integration after deploying latest web3 code from PR branch:

```
    I successfully create an erc contract from contract bytes with balance 0
    I create a new token with freeze status 2 and kyc status 1
    I create a new nft with supplyType "INFINITE"
    I mint a serial number
    the mirror node REST API should return status 200 for the erc contract transaction
    I call the erc contract via the mirror node REST API for token name
    I call the erc contract via the mirror node REST API for token symbol
    I call the erc contract via the mirror node REST API for token decimals
    I call the erc contract via the mirror node REST API for token totalSupply
    I call the erc contract via the mirror node REST API for token ownerOf
    I call the erc contract via the mirror node REST API for token tokenUri
    I call the erc contract via the mirror node REST API for token getApproved
    I call the erc contract via the mirror node REST API for token allowance
    I call the erc contract via the mirror node REST API for token isApprovedForAll
    I call the erc contract via the mirror node REST API for token balance
    I approve "BOB" for nft
    the mirror node REST API should return status 200 for the erc contract transaction
    I call the erc contract via the mirror node REST API for token getApproved with response BOB <- 
    expected: "0000000000000000000000000000000000001521"
     but was: "2420128de6f88d233dff1a8a1bc0235d47847a19"
    I approve "ALICE" for nft all serials
    the mirror node REST API should return status 200 for the erc contract transaction
    I call the erc contract via the mirror node REST API for token isApprovedForAll with response true
    I approve "ALICE" with 2
    the mirror node REST API should return status 200 for the erc contract transaction
    I call the erc contract via the mirror node REST API for token allowance with allowances
    I call the erc contract via the mirror node REST API for token isApprovedForAll with response true with alias accounts
    I call the erc contract via the mirror node REST API for token allowance with alias accounts
    I call the erc contract via the mirror node REST API for token balance with alias account
     org.opentest4j.AssertionFailedError: 
    expected: "0000000000000000000000000000000000001521"
     but was: "2420128de6f88d233dff1a8a1bc0235d47847a19"
        at jdk.internal.reflect.GeneratedConstructorAccessor95.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at com.hedera.mirror.test.e2e.acceptance.steps.ERCContractFeature.verifyNftAllowance(ERCContractFeature.java:319)
        at ✽.I call the erc contract via the mirror node REST API for token getApproved with response BOB(classpath:features/contract/erc.feature:22
```

```
    I approve "BOB" to transfer up to 100 tℏ
    the mirror node REST API should confirm the approved 100 tℏ crypto allowance
    I send 1 tℏ to "ALICE"
    the mirror node REST API should return status 200 for the crypto transfer transaction
    the new balance should reflect cryptotransfer of 1
    the mirror node REST API should confirm the approved 100 tℏ crypto allowance
    "BOB" transfers 1 tℏ from the approved allowance to "ALICE"
    the mirror node REST API should confirm the approved transfer of 1 tℏ <- 
    Expected size: 1 but was: 2 in:
    [MirrorTransaction(assessedCustomFees=[], consensusTimestamp=1695062781.477890002, entityId=0.0.5409, name=CRYPTOUPDATEACCOUNT, nftTransfers=[], result=SUCCESS, scheduled=false, tokenTransfers=[], transactionId=0.0.5409-1695062769-130081164, transfers=[], validStartTimestamp=1695062769.130081164),
        MirrorTransaction(assessedCustomFees=[], consensusTimestamp=1695062781.477890003, entityId=null, name=CRYPTOTRANSFER, nftTransfers=[], result=SUCCESS, scheduled=false, tokenTransfers=[], transactionId=0.0.5409-1695062769-130081164, transfers=[MirrorTransfer(account=0.0.3, amount=955, isApproval=false), MirrorTransfer(account=0.0.98, amount=82101, isApproval=false), MirrorTransfer(account=0.0.5403, amount=-1, isApproval=true), MirrorTransfer(account=0.0.5409, amount=-83056, isApproval=false), MirrorTransfer(account=0.0.5421, amount=1, isApproval=false)], validStartTimestamp=1695062769.130081164)]
    the mirror node REST API should confirm the approved allowance of 100 tℏ was debited by 1 tℏ
    I approve "BOB" to transfer up to 100 tℏ
    the mirror node REST API should confirm the approved 100 tℏ crypto allowance
    I delete the crypto allowance for "BOB"
    the mirror node REST API should confirm the crypto allowance no longer exists
```

```
    2023-09-18T18:47:18.778Z ERROR ForkJoinPool-1-worker-8 c.h.m.t.e.a.s.EstimatePrecompileFeature Scenario failure: 
    I create estimate precompile contract with 0 balancepped
    I create erc test contract with 0 balance
    I successfully create Precompile contract with 0 balance
    I successfully create fungible tokens
    I successfully create non fungible tokens
    I mint and verify a new nft
    the mirror node REST API should return status 200 for the HAPI transaction
    I set lower deviation at 5% and upper deviation at 20%
    I call estimateGas with associate function for fungible token
    I call estimateGas with associate function for NFT
    I call estimateGas with dissociate token function without association for fungible token
    I call estimateGas with dissociate token function without association for NFT
    I call estimateGas with nested associate function that executes it twice for fungible token
    I call estimateGas with nested associate function that executes it twice for NFT
    I associate the receiver account with the fungible token
    the mirror node REST API should return status 200 for the HAPI transaction
    I call estimateGas with dissociate token function for fungible token <- 400 Bad Request from POST https://integration.mirrornode.hedera-ops.com/api/v1/contracts/call
    I associate the receiver account with the NFT
```

2023-09-19 10:56 UTC, 0xivanov commented
@steven-sheehy 
I have identified some of the problems.

1.  When we create operator account in the acceptance tests, we do not set alias for the account (if it has ecdsa key) and this causes the mirror node to return long zero address, which fails the asserts.
2. GetApproved operation in web3 always returns long zero address (a bug). Will be fixed here: https://github.com/hashgraph/hedera-mirror-node/pull/6896

2023-09-19 15:20 UTC, steven-sheehy approved these changes
LGTM. Confirmed it works against integration.

2023-09-19 15:21 UTC, merged