feat: Add custom web3j plugin from jitpack
hiero-ledger/hiero-mirror-node pull request #8827
Opened 2024-07-19 15:00 UTC by kselveliev

**Description**:
This Pr add the custom web3j-plugin that has generateBoth config that we need. 
Release of custom plugin is made in jitpack made from https://github.com/kselveliev/web3j-gradle-plugin/tree/add-generate-both-flag-jitpack

This PR modifies
build.gradle adds new custom plugin

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

2024-07-19 20:39 UTC, steven-sheehy requested changes

2024-07-19 20:39 UTC, steven-sheehy commented on hedera-mirror-test/build.gradle.kts
> +web3j {
I don't think we should add web3j to acceptance tests until we're actually going to start using it.

2024-07-19 20:39 UTC, steven-sheehy commented on hedera-mirror-web3/build.gradle.kts
> +    implementation("org.web3j:core:4.12.0")
Revert. Versions go in root build.gradle.

2024-07-19 20:39 UTC, steven-sheehy commented on build.gradle.kts
> -    set("org.web3j", "4.12.0")
Revert

2024-07-19 20:39 UTC, steven-sheehy commented on build.gradle.kts
> +    maven { url = uri("https://jitpack.io") }
We only need jitpack for the custom gradle plugin, so this should not need to be added to regular repositories.

2024-07-19 20:39 UTC, steven-sheehy commented on build.gradle.kts
> +}
Believe this isn't necessary and duplicates the similar config in buildSrc/build.gradle.kts

2024-07-19 20:39 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +                contract.call_isTokenFrozen(tokenAddress, senderAddress).send();
web3j generates them with this `call_` prefix?

2024-07-19 20:39 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> -        var result = (TransactionReceiptCustom)
We should delete the TransactionReceiptCustom class now.

2024-07-19 20:39 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/solidity/HederaResponseCodes.sol
> +pragma solidity ^0.8.18;
Why does it not work with later solidity version?

2024-07-19 20:39 UTC, steven-sheehy commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +        var result = contract.call_getTokenKeyPublic(tokenAddress, keyType);
With this new approach, do we still need to implement all the different RPC methods in the web3j service? We should check if we can remove any now. For example, for call we shouldn't need send or nonce.

2024-07-22 06:40 UTC, IvanKavaldzhiev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +        var result = contract.call_getTokenKeyPublic(tokenAddress, keyType);
To do so, we should revisit the way we deploy contracts with the web3j plugin. The internal web3j `deploy` method sends a transaction that returns `TransactionReceipt`, hence it will require all these helper methods.

If we stop using the generated `deploy()` methods and refactor the `TestWeb3Service.sendTopLevelContractCreate` to not populate `TransactionReceipt` and just:

- directly calls `contractExecutionService.processCall`
- insert the returned runtime bytecode in DB

Then we would be able to remove a lot of the logic from `TestWeb3jService`.

2024-07-22 08:18 UTC, kselveliev commented on hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/ContractCallServicePrecompileTest.java
> +                contract.call_isTokenFrozen(tokenAddress, senderAddress).send();
Yes

2024-07-22 08:23 UTC, kselveliev commented on hedera-mirror-web3/src/test/solidity/HederaResponseCodes.sol
> +pragma solidity ^0.8.18;
It works with later version. For historical tests we are loading older evm version and our contracts used in historical test were compiled with 8.18 of solidity in order to work. Using 8.18 ensures that historical and latest tests will be working. Otherwise if we use latest version historical tests will most likely start failing.

2024-07-22 11:18 UTC, kselveliev commented on hedera-mirror-test/build.gradle.kts
> +web3j {
Comment addressed. I actually experimented with it in the test module but then forgot to remote it.

2024-07-22 13:40 UTC, kselveliev commented on hedera-mirror-web3/build.gradle.kts
> +    implementation("org.web3j:core:4.12.0")
Comment addressed

2024-07-22 13:40 UTC, kselveliev commented on build.gradle.kts
> -    set("org.web3j", "4.12.0")
Comment addressed

2024-07-22 13:41 UTC, kselveliev commented on build.gradle.kts
> +    maven { url = uri("https://jitpack.io") }
Comment addressed

2024-07-22 13:41 UTC, kselveliev commented on build.gradle.kts
> +}
Comment addressed

2024-07-22 15:43 UTC, kselveliev commented
Closing in favor of https://github.com/hashgraph/hedera-mirror-node/pull/8848

2024-07-22 15:43 UTC, closed without merging